### ISSUE TITLE
Giving access to user API key on the IATI Registry

### ISSUE THREAD

**Issue by PetyaKangalova** [ViderumGlobal/ckanext-iati#114]
At the moment the IATI technical team is unable to see the user API key on the IATI Registry. On a number of occasions users are unable to find where the API key is positioned. It will be really useful if the IATI technical team is also able to see the API key so that we can assist publishers, especially when they need to add the API key to their AidStream accounts. 

Would it be possible to make that change?

**Comment by pmartignoli** [comment]
@PetyaKangalova. We can make the API keys visible to all sysadmins which would require 2 hours to implement and test. If you would like us to go ahead with this please let me know. If IATI would like to limit access to user API keys to a subset of sysadmins, it would also be possible but require more work, involving creating a new role and a process for assigning users to that role, and adding a call to the API or adapting a template so that it's possible to update which users have the extra rights while the portal is running.

**Comment by PetyaKangalova** [comment]
@pmartignoli  Many thanks for your response and specifying the time that it will take to undertake this task.  In terms of giving permissions to a subset of sysadmins I don't think this is necessary and I think we will be happy to go ahead with the option of all sysadmins having access to user API keys.  I suggest that you add the time to the Viderum IATI Registry Support Days Tracking and then @dalepotter  can confirm whether he is happy to give the go ahead during the call this Friday.

**Comment by dalepotter** [comment]
Thanks for the update on timings @pmartignoli - yes let's go ahead with this one.

**Comment by pmartignoli** [comment]
@dalepotter @PetyaKangalova this is deployed. Please test and get back to me if there are any issues.

**Comment by PetyaKangalova** [comment]
@pmartignoli  Thanks for the update. Strangely, yesterday morning I wasn't able to see the API key. I just checked this morning on a few publishers and can confirm that I can now see the API key.  I will check again next week just to make sure it is working properly and will then close the issue.

**Comment by PetyaKangalova** [comment]
I can confirm that we can now see the user API key so I am closing this issue.
