### ISSUE TITLE
IATI Registry datasets search- failed validation for File Type

### ISSUE THREAD

**Issue by PetyaKangalova** [ViderumGlobal/ckanext-iati#127]
It has been flagged by users of IATI data (see Twitter discussion in [here](https://twitter.com/andylolz/status/880731702863302656)) that there is an error with Registry search page.

The [IATI Registry dataset search page](https://iatiregistry.org/dataset) currently returns multiple entries for   activities and organisations under File type. It has been identified that this is likely due to lack of validation through the CKAN API. Could you please look into this and add the appropriate validation?

**Comment by PetyaKangalova** [comment]
I can see on the [ IATI Registry dataset search page](https://iatiregistry.org/dataset) that the drop down for File Type now shows correctly only activity and organisation as an option. Could you confirm whether the issue has been fixed and close it accordingly?

**Comment by pmartignoli** [comment]
Hi @PetyaKangalova 
A validation check was added for the "File type" field, meaning the existing datasets with an invalid value for the "File type" field had to be corrected. Custom scripts (for each incorrect value) were developed in order to find the datasets and replace the value. After the scripts were run and tested locally and on the staging portal, they were deployed to production. 

I will close this issue
