### ISSUE TITLE
Dashboard > My Datasets - no pagination 

### ISSUE THREAD

**Issue by stevieflow** [ViderumGlobal/ckanext-iati#66]
When logged in, f I go to http://iatiregistry.org/dashboard/datasets, I see a list of datasets, but function to list the next page of results

**Comment by amercader** [comment]
Adding pagination to this page is not trivial because of how it works internally. There is a hard limit of 50 datasets on CKAN core. Changing this and adding pagination would be involve extending it, which wouldn’t be easy.

**Comment by stevieflow** [comment]
Thanks.

OK - guess we should just leave this open for now.  Quite a few IATI publishers have more than 50 datasets, but appreciate that this seems to be a major work

**Comment by dalepotter** [comment]
Just looking at some old issues to work out next steps. 

To add clarity on what this issue is, this is a feature idea to add pagination to the 'Manage my datasets' page that I see if I am a publisher of many datasets.  For example, this is what I would see if I were the viewing the edit page as `unitedstates`:

![unitedstates-datasets](https://cloud.githubusercontent.com/assets/8247168/26246584/db6ee6b8-3c91-11e7-84ce-9c119040dde6.png)

**Comment by dalepotter** [comment]
Having looked at this one I personally feel it won't add much benefit to paginate the results, especially since dataset names are listed alphabetically.  Therefore I'm closing this issue for now.

@PetyaKangalova @amy-silcock @hayfield @wendyrogers - feel free to reopen this issue if you think this is worth taking forwards, based on experiences with publishers.
