### ISSUE TITLE
Install an SSL certificate on the Registry domain

### ISSUE THREAD

**Issue by Mattdevinit** [ViderumGlobal/ckanext-iati#74]
and set up a redirect to send all traffic accessing via HTTP to HTTPS please

**Comment by dalepotter** [comment]
This is now 95%, although there is a small 'insecure content warning' issue to be resolved: http://discuss.iatistandard.org/t/iati-registry-now-using-https/511/6

When resolved, this issue can be closed.

**Comment by dalepotter** [comment]
Alongside #79, we understand that this should be resolved when the IATI Registry is [upgraded to a newer CKAN version](http://www.aidtransparency.net/news/important-changes-to-the-iati-registry-api) in October, meaning that a fix will take some time and would only exist for 4-6 weeks. Therefore, this issue is being marked as a #wontfix for now.

**Comment by chrisviderum** [comment]
@dalepotter do we face any issues with the SSL certificate? 

The alphabetical ordering on the publisher page should work, too.

**Comment by dalepotter** [comment]
A fix for this issue has been deployed to the live instance of the IATI Registry. Therefore this issue is being closed.
