### ISSUE TITLE
Registry Not Handling 'Missing' File Correctly

### ISSUE THREAD

**Issue by wendyrogers** [ViderumGlobal/ckanext-iati#81]
This issue has been raised from a Zendesk ticket (3834)

Plan Netherlands has a dataset that contains an invalid URL to a file. However, the Registry is displaying the dataset information in an 'strange way - see https://iatiregistry.org/dataset/plannlno-89

 @peppe1337 - please could you investigate. TIA

**Comment by dalepotter** [comment]
Just taking a look through the GH issues... @peppe1337 is there any update on this one?

**Comment by peppe1337** [comment]
@dalepotter @wendyrogers  do we have an open ticket for this one? I just checked on ZenDesk, but couldn't find one, which was created in the last ten days. (Except the slow accessibility)

I will add this as a task for us to check and solve!

**Comment by wendyrogers** [comment]
@peppe1337 As there is only one dataset I would expect the details of the dataset to be displayed with a message to say that the resource (specified in the URL of the dataset) is missing? The Registry did use to do this?

Also I have resent the email that this issues was raised from. TIA

**Comment by chrisviderum** [comment]
As an update here.

We have updated the 2.5.2 portal with a fix regarding this issue. The data archiver had a minor issue which causes this problem.

We deleted this specific dataset on the new portal, because the publisher tried to delete it months ago:  https://iati-staging.ckan.io/dataset/plannlno-89

**Comment by dalepotter** [comment]
Thanks for the update on this one @chrisviderum

**Comment by wendyrogers** [comment]
Thanks for update @chrisviderum . Also would it be a quick fix to also apply it to the live Registry as well?

**Comment by chrisviderum** [comment]
@wendyrogers in general every fix on the "live registry is a bit complicated at the moment, because we don't have a real development environmnet for it anymore and through the older CKAN version our development team runs over and over again into issues while running it on their local machines.

I think it wouldn't be a quick fix to the live registry. So I would ask to wait for the migration to the new portal.

**Comment by wendyrogers** [comment]
Ok and thanks for the information @chrisviderum. We will wait for the migration then.

**Comment by dalepotter** [comment]
Hi @chrisviderum, was just reviewing this one. I'm not sure if I understood correctly but should the fix applied to v2.5.2 (i.e. the staging version) resolve this issue?  When just clicking through to the link in your response on [13th September](https://github.com/okfn/ckanext-iati/issues/81#issuecomment-246622095), the bug still seems to appear: 

![image](https://cloud.githubusercontent.com/assets/8247168/18672549/7af16770-7f40-11e6-92a1-23eee0827fec.png)

Perhaps I missed something and the fix is not ready yet. I've tried a hard refresh and a different browser too.

**Comment by chrisviderum** [comment]
@dalepotter thanks for your post. We will check this, but my first guess that this is a result of the database migration some days ago.

The archiver had some problems which we fixed. With the database we migrated this "broken" dataset to the new portal. Our fix prevents like that doesn't happen in the future anymore.

After we have done the last database migration we will delete this dataset.

Best,

Chris

**Comment by chrisviderum** [comment]
@dalepotter @wendyrogers 

Can we close this ticket?

**Comment by wendyrogers** [comment]
@chrisviderum yes okay to close now

**Comment by dalepotter** [comment]
A fix for this issue has been deployed to the live instance of the IATI Registry. Therefore this issue is being closed.
